export const AppRoles: { [key: string]: string } = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
  AUTHOR: 'AUTHOR',
  ORGANISATION: 'ORGANISATION',
  PENDING_ORGANISATION: 'PENDING_ORGANISATION',
};
